### ISSUE TITLE
[DISCUSS] Visual Studio Code Integration

### ISSUE THREAD

**Issue by cwharris** [trxcllnt/rapids-compose#1]
VS Code integration has the potential to increase productivity, decrease on-boarding, and increase community involvement.

What rapids-compose features would you like to see exposed in vs code?

- [ ] Shortcuts and/or buttons for test and benchmark

**Comment by trxcllnt** [comment]
`control+shift+B` build shortcuts with C++/CUDA problem-matchers added in https://github.com/trxcllnt/rapids-compose/commit/790ebbc4af4bee4e80222acbddb545326fde1800.
