### ISSUE TITLE
[FEA] Add raft to rapids-compose

### ISSUE THREAD

**Issue by seunghwak** [trxcllnt/rapids-compose#10]
cuGraph and cuML are dependent on raft (https://github.com/rapidsai/raft), and can raft to be added to rapids-compose?

**Comment by trxcllnt** [comment]
Yes, definitely @seunghwak! Does it need to be added as a project for development, or is it a system or conda dependency?

**Comment by seunghwak** [comment]
There are people working on updating raft (including myself), so I think this needs to be a project.

**Comment by trxcllnt** [comment]
In this branch https://github.com/trxcllnt/rapids-compose/tree/add/raft/ until https://github.com/rapidsai/raft/pull/13 is merged.
