### ISSUE TITLE
docker-compose `make init` fails silently when github API limit is reached

### ISSUE THREAD

**Issue by thomcom** [trxcllnt/rapids-compose#3]
I'm using rapids-compose behind a VPN. The Github API limit has been reached for the IP address that I appear as behind the VPN. When `install_docker_compose()` runs, the `qj -r ".tag_name"` results in a `null` response, which is then used in the curl request to actually pull `docker-compose` from its repository. This results in an empty file being written `/usr/local/bin`, breaking future use of `rapids-compose`.

I'm writing a solution that makes the API request into a variable, checks the variable for error status and uses `exit -1` with a status message if so, otherwise continuing as normal.

**Comment by trxcllnt** [comment]
Ah, yeah that's an issue I dealt with installing github-cli as well. My workaround was to default to a known-good release, and let people update it later if they need. I forgot to go back and do this for all the places that pull their versions from github:

https://github.com/trxcllnt/rapids-compose/blob/c7cae66bab611acfa46e4c938cead7ac93bb326f/scripts/04-clone-rapids-repositories.sh#L46-L50

**Comment by trxcllnt** [comment]
Done in 7fcd1dedfc4b5be475f6e84b78ff5b4dc1bb7846. Thanks @thomcom!
