### ISSUE TITLE
Detect vscode-insiders if it is installed but vscode is not

### ISSUE THREAD

**Issue by harrism** [trxcllnt/rapids-compose#5]
Currently when you make init if vscode is not installed, but vscode-insiders is, compose installs vscode.  It would be nice to support both.

**Comment by cwharris** [comment]
It makes sense that installing vscode isn't necessary if insiders is already installed. Outside of installing vscode along side insiders, does this effect workflow? Wondering if the problem extends past having to install the extra dependencies.
